In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:

df1=pd.read_csv('https://raw.githubusercontent.com/UNCG-DAISY/Tiny_Gesture/main/data/jump_set.csv')
df2=pd.read_csv('https://raw.githubusercontent.com/UNCG-DAISY/Tiny_Gesture/main/data/other_set.csv')
df3=pd.read_csv('https://raw.githubusercontent.com/UNCG-DAISY/Tiny_Gesture/main/data/run_set.csv')
df4=pd.read_csv('https://raw.githubusercontent.com/UNCG-DAISY/Tiny_Gesture/main/data/squat_set.csv')
df5=pd.read_csv('https://raw.githubusercontent.com/UNCG-DAISY/Tiny_Gesture/main/data/walk_set.csv')


In [3]:
df1['gesture']=1
df2['gesture']=2
df3['gesture']=3
df4['gesture']=4
df5['gesture']=5

In [5]:
df=pd.concat([df1,df2,df3,df4,df5],axis=0)

In [6]:

df.head()

aX     aY     aZ      gX      gY       gZ  gesture
0 -0.868 -0.676  0.086 -60.364  62.622   97.839        1
1 -0.777 -0.677  0.109 -58.716  79.651  104.553        1
2 -0.737 -0.622  0.066 -40.039  61.951  102.356        1
3 -0.727 -0.403  0.017 -14.832  33.936   95.459        1
4 -0.689 -0.249 -0.048   6.348  14.771   86.975        1

In [7]:
d=pd.get_dummies(df,columns=['gesture'])


In [8]:
d

aX     aY     aZ      gX  ...  gesture_2  gesture_3  gesture_4  gesture_5
0     -0.868 -0.676  0.086 -60.364  ...          0          0          0          0
1     -0.777 -0.677  0.109 -58.716  ...          0          0          0          0
2     -0.737 -0.622  0.066 -40.039  ...          0          0          0          0
3     -0.727 -0.403  0.017 -14.832  ...          0          0          0          0
4     -0.689 -0.249 -0.048   6.348  ...          0          0          0          0
...      ...    ...    ...     ...  ...        ...        ...        ...        ...
11895 -0.983 -0.046 -0.069   2.747  ...          0          0          0          1
11896 -0.985 -0.043 -0.071   3.174  ...          0          0          0          1
11897 -0.984 -0.042 -0.061   2.991  ...          0          0          0          1
11898 -0.983 -0.050 -0.063   2.808  ...          0          0          0          1
11899 -0.977 -0.043 -0.061   3.479  ...          0          0          0          1

[59500 rows x 11 columns]

In [9]:
from sklearn.model_selection import train_test_split

In [10]:
x=d[['aX','aY','aZ','gX','gY','gZ']]
y=d[['gesture_1','gesture_2','gesture_3','gesture_4','gesture_5']]

In [11]:
x.shape

(59500, 6)

In [12]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.33, random_state=42)


In [13]:
y_train


gesture_1  gesture_2  gesture_3  gesture_4  gesture_5
7720          0          0          1          0          0
5489          1          0          0          0          0
2065          0          0          0          1          0
6982          0          0          0          1          0
3940          0          0          0          0          1
...         ...        ...        ...        ...        ...
6743          0          0          0          0          1
2458          0          0          0          1          0
860           1          0          0          0          0
3895          0          1          0          0          0
8822          0          0          0          0          1

[39865 rows x 5 columns]

In [14]:
from sklearn.preprocessing import MinMaxScaler


In [15]:

sc=MinMaxScaler()

In [17]:
sc.fit(x_train)


MinMaxScaler(copy=True, feature_range=(0, 1))

In [18]:
x_train=sc.transform(x_train)


In [19]:
x_test=sc.transform(x_test)


In [20]:
y_test

gesture_1  gesture_2  gesture_3  gesture_4  gesture_5
10289          1          0          0          0          0
2128           0          0          1          0          0
10880          1          0          0          0          0
3894           0          0          1          0          0
9311           1          0          0          0          0
...          ...        ...        ...        ...        ...
9318           0          0          0          1          0
10411          0          0          0          1          0
4226           1          0          0          0          0
4185           1          0          0          0          0
9037           1          0          0          0          0

[19635 rows x 5 columns]

In [21]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,Dropout

In [22]:
model=Sequential()
model.add(Dense(512,activation='relu',input_dim=6))
model.add(Dense(256,activation='relu'))
model.add(Dense(128,activation='relu'))

model.add(Dense(5,activation='softmax'))
model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])

In [23]:

model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 512)               3584      
_________________________________________________________________
dense_1 (Dense)              (None, 256)               131328    
_________________________________________________________________
dense_2 (Dense)              (None, 128)               32896     
_________________________________________________________________
dense_3 (Dense)              (None, 5)                 645       
Total params: 168,453
Trainable params: 168,453
Non-trainable params: 0
_________________________________________________________________


In [24]:
model.fit(x=x_train,y=y_train,epochs=5)

Epoch 1/5
1246/1246 [==============================] - 5s 4ms/step - loss: 1.3120 - accuracy: 0.3951
Epoch 2/5
1246/1246 [==============================] - 5s 4ms/step - loss: 0.9501 - accuracy: 0.5788
Epoch 3/5
1246/1246 [==============================] - 5s 4ms/step - loss: 0.7732 - accuracy: 0.6674
Epoch 4/5
1246/1246 [==============================] - 5s 4ms/step - loss: 0.7262 - accuracy: 0.6904
Epoch 5/5
1246/1246 [==============================] - 5s 4ms/step - loss: 0.6894 - accuracy: 0.7102


In [25]:
p=model.predict(x_test)

In [26]:
p

array([[1.5988383e-01, 1.9969069e-10, 4.7562385e-01, 1.4391217e-01,
        2.2058015e-01],
       [2.2805677e-01, 5.2837333e-07, 4.5286459e-01, 1.7253613e-01,
        1.4654198e-01],
       [4.4998154e-01, 2.0521432e-07, 2.0945482e-01, 1.8381079e-01,
        1.5675260e-01],
       ...,
       [4.8176485e-01, 4.5450674e-06, 1.6990985e-01, 1.8861951e-01,
        1.5970129e-01],
       [1.8070245e-01, 2.8054179e-05, 8.1926507e-01, 3.5157683e-08,
        4.4990143e-06],
       [2.9304552e-01, 6.4093700e-07, 1.7676699e-01, 1.0080650e-01,
        4.2938045e-01]], dtype=float32)

In [29]:
pp=p.argmax(axis=1)
j=y_test.values
jj=j.argmax(axis=1)
len(jj[jj==1])


3867

In [30]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(jj,pp))


[[2750    9  438  433  357]
 [   4 3694   12    1  156]
 [ 695   10 2193  754  227]
 [1084   13  302 2393  115]
 [ 229   17   73   24 3652]]
